### ISSUE TITLE
Ready to use script for CALVADOS3

### ISSUE THREAD

**Issue by riccardocapelli** [KULL-Centre/_2024_Cao_CALVADOSCOM#1]
I read the preprint on biorXiv and I really liked the approach of CALVADOS3 for modeling partially structured proteins. 

In particular, I am interested in simulating some proteins with IDRs in them using this approach, and I was wondering if there is (or is planned) a colab/jupyter notebook/python script to run a CALVADOS3 simulation given sequence, pH, temperature, and the folded domains.

Thanks a lot!

Riccardo

**Comment by fancaoErik** [comment]
Hi Riccardo!
Thanks for your interest. I suppose you have already received an email from Kresten regarding your question. Please close the issue if the answer in the email makes sense to you. Or I will do it later on. :)
Fan

**Comment by riccardocapelli** [comment]
Hi Fan!

Thanks for your answer. At the moment I have not received any email, I will let you know if I receive it!

Thanks again!

Riccardo

**Comment by fancaoErik** [comment]
Hi Riccardo. I made a simple script called `simple_singlechain.py`. You can use this script to do a quick simulation of your protein with CALVADOS3 parameters. Remember to modify the second block as you need. Feel free to leave a message if you have any questions.

**Comment by riccardocapelli** [comment]
Hi Fan,

Thanks for the nice and clean script, it is exactly what I imagined at the beginning. I still have a small issue: at like 67, you have:

` create_parameters(cwd, dataset, cycle, initial_type)`

in the end, the script is trying to read the file `/projects/prism/people/ckv176/_2024_Cao_CALVADOSCOM/src/CALVADOS3COM_2.0_1/residues_pub.csv`, is this file equivalent to the `residues_pub.csv` in the `src` folder or is it a different version?

Thanks again!

Riccardo

**Comment by fancaoErik** [comment]
They are the same. The file is copied from `src` in line 66:
`os.system(f"cp {cwd}/residues_pub.csv {cwd}/{dataset}")`
Remember to change `cwd` into your own path to `simple_singlechain.py`

Fan

**Comment by riccardocapelli** [comment]
Fantastic, thank you so much for adding the script in this repository!
