### ISSUE TITLE
A trouble about submit jobs by used "python3 simple_singlechain.py"

### ISSUE THREAD

**Issue by Martialnb** [KULL-Centre/_2024_Cao_CALVADOSCOM#2]
Hello! I'm using CALVADOS3 trying to run my protein simulation, and after modifying the code, I get an error after typing "python3 simple_singlechain.py" with the following message:
Traceback (most recent call last):
  File "simple_singlechain.py", line 126, in <module>
    ray.get([simulate_simple.remote(yaml.safe_load(open(f"{cwd}/{dataset}/{record}/{cycle}/config_{replica}.yaml", 'r'))) for replica in replicas_list4MD])
  File "/home/chenyt/miniconda3/envs/CALVADOS3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/chenyt/miniconda3/envs/CALVADOS3/lib/python3.8/site-packages/ray/_private/worker.py", line 2275, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::simulate_simple() (pid=1396361, ip=172.21.54.173)
  File "/home/chenyt/lrj/_2024_Cao_CALVADOSCOM-main/src/utils.py", line 904, in simulate_simple
    ssdomains = get_ssdomains(name, fdomains)
  File "/home/chenyt/lrj/_2024_Cao_CALVADOSCOM-main/src/protein_repo.py", line 50, in get_ssdomains
    if isinstance(domain[0], int):
TypeError: 'int' object is not subscriptable

I have no idea how to solve it. Can you help me with this? Thanks a lot!

**Comment by fancaoErik** [comment]
Hi Martialnb! Thanks for playing with CALVADOS. Could you please check your `domain_boundaries` variable in line31 in `simple_singlechain.py`?
I am guessing the possible reason why you got this error is that something went wrong with your boundaries.
If you have only one domain, it should be [[a,b]]. Note that it is a nested list; it should not be [a,b];
If you have more than one domain, it should be [[a,b],[c,d]...].
Hope this would help you. Leave a message if you are still having this problem.

Fan

**Comment by Martialnb** [comment]
> Hi Martialnb! Thanks for playing with CALVADOS. Could you please check your `domain_boundaries` variable in line31 in `simple_singlechain.py`? I am guessing the possible reason why you got this error is that something went wrong with your boundaries. If you have only one domain, it should be [[a,b]]. Note that it is a nested list; it should not be [a,b]; If you have more than one domain, it should be [[a,b],[c,d]...]. Hope this would help you. Leave a message if you are still having this problem.
> 
> Fan

Thank you for your reply! I just checked my `domain_boundaries` and modified it, it works!

**Comment by fancaoErik** [comment]
I am closing this one.
